-- D1 migration. No automatic migration or deployment.
CREATE TABLE control (id INTEGER PRIMARY KEY CHECK(id=1), enabled INTEGER NOT NULL DEFAULT 0, epoch INTEGER NOT NULL DEFAULT 0);
INSERT INTO control VALUES(1,0,0);
CREATE TABLE auth (id TEXT PRIMARY KEY, kind TEXT NOT NULL, payload TEXT NOT NULL, expires INTEGER NOT NULL, used INTEGER NOT NULL DEFAULT 0);
CREATE TABLE rates (id TEXT PRIMARY KEY, n INTEGER NOT NULL, expires INTEGER NOT NULL);
CREATE TABLE nonces (id TEXT PRIMARY KEY, expires INTEGER NOT NULL);
CREATE TABLE queue (seq INTEGER PRIMARY KEY AUTOINCREMENT, id TEXT UNIQUE NOT NULL, principal TEXT NOT NULL, hash TEXT NOT NULL, envelope TEXT, received INTEGER NOT NULL, expires INTEGER NOT NULL, ack INTEGER, backup TEXT);
CREATE TABLE audit (seq INTEGER PRIMARY KEY AUTOINCREMENT, at INTEGER NOT NULL, kind TEXT NOT NULL, ref TEXT NOT NULL);
CREATE TRIGGER audit_no_update BEFORE UPDATE ON audit BEGIN SELECT RAISE(ABORT,'append-only'); END;
CREATE TRIGGER queue_no_change BEFORE UPDATE OF id,principal,hash,received ON queue BEGIN SELECT RAISE(ABORT,'immutable-receipt'); END;
CREATE TRIGGER intake_enabled BEFORE INSERT ON queue WHEN (SELECT enabled FROM control WHERE id=1)!=1 BEGIN SELECT RAISE(ABORT,'disabled'); END;
CREATE TRIGGER queue_size BEFORE INSERT ON queue WHEN (SELECT coalesce(sum(length(envelope)),0) FROM queue)+length(NEW.envelope)>157286400 BEGIN SELECT RAISE(ABORT,'capacity'); END;

