/* Expand this graph by adding nodes and links. IDs must be unique. */
window.KNOWLEDGE_GRAPH = {
  categories: [
    { id: "business", label: "Business", color: "#63e6be" },
    { id: "ai-tech", label: "AI / Tech", color: "#74c0fc" },
    { id: "everquest", label: "EverQuest", color: "#ffd43b" },
    { id: "media-closet", label: "Media / Closet", color: "#da77f2" },
    { id: "automotive", label: "Automotive", color: "#ff8787" },
    { id: "real-estate", label: "Real Estate", color: "#ffa94d" },
    { id: "finance", label: "Finance", color: "#94d82d" },
    { id: "health-fitness", label: "Health / Fitness", color: "#38d9a9" },
    { id: "personal", label: "Personal", color: "#b197fc" }
  ],
  nodes: [
    { id: "knowledge-hub", label: "Knowledge Hub", category: "personal", description: "A central map for connecting ideas, interests, projects, and useful discoveries." },
    { id: "strategy", label: "Business Strategy", category: "business", description: "Frameworks for priorities, positioning, execution, and sustainable growth." },
    { id: "operations", label: "Smart Operations", category: "business", description: "Repeatable systems, clear workflows, and practical automation." },
    { id: "customer-insight", label: "Customer Insight", category: "business", description: "Learning from customer needs, behavior, feedback, and outcomes." },
    { id: "generative-ai", label: "Generative AI", category: "ai-tech", description: "Tools and techniques for creating, reasoning, and building with modern AI." },
    { id: "knowledge-systems", label: "Knowledge Systems", category: "ai-tech", description: "Structures that make information easier to find, connect, and apply." },
    { id: "automation", label: "Workflow Automation", category: "ai-tech", description: "Using software to reduce repetitive work and strengthen reliable processes." },
    { id: "norrath", label: "World of Norrath", category: "everquest", description: "Exploration, lore, and the enduring world of EverQuest." },
    { id: "raid-strategy", label: "Raid Strategy", category: "everquest", description: "Coordination, preparation, roles, and group problem-solving." },
    { id: "game-economy", label: "Game Economy", category: "everquest", description: "Trading, scarcity, crafting, and value inside a virtual world." },
    { id: "media-library", label: "Media Library", category: "media-closet", description: "A browsable collection of films, series, music, and memorable references." },
    { id: "wardrobe-system", label: "Wardrobe System", category: "media-closet", description: "Organizing clothing by use, season, style, and versatility." },
    { id: "visual-storytelling", label: "Visual Storytelling", category: "media-closet", description: "How images, styling, and sequences communicate an idea." },
    { id: "vehicle-design", label: "Vehicle Design", category: "automotive", description: "The meeting point of engineering, aesthetics, usability, and identity." },
    { id: "maintenance", label: "Preventive Maintenance", category: "automotive", description: "Regular care that improves reliability, safety, and long-term value." },
    { id: "future-mobility", label: "Future Mobility", category: "automotive", description: "Electric vehicles, intelligent systems, and evolving transportation." },
    { id: "property-analysis", label: "Property Analysis", category: "real-estate", description: "Evaluating location, condition, costs, risks, and potential." },
    { id: "home-projects", label: "Home Projects", category: "real-estate", description: "Improvements that balance daily usefulness, craft, and lasting value." },
    { id: "neighborhoods", label: "Neighborhood Patterns", category: "real-estate", description: "How access, community, development, and amenities shape places." },
    { id: "investing", label: "Long-Term Investing", category: "finance", description: "Patient capital allocation guided by goals, evidence, and risk awareness." },
    { id: "financial-systems", label: "Financial Systems", category: "finance", description: "Simple routines for planning, tracking, saving, and making decisions." },
    { id: "risk", label: "Risk & Resilience", category: "finance", description: "Preparing for uncertainty with buffers, diversification, and clear tradeoffs." },
    { id: "strength", label: "Strength Training", category: "health-fitness", description: "Progressive movement for capability, confidence, and durable health." },
    { id: "recovery", label: "Recovery & Sleep", category: "health-fitness", description: "Rest, adaptation, and sustainable rhythms that support performance." },
    { id: "nutrition", label: "Practical Nutrition", category: "health-fitness", description: "Repeatable eating habits centered on energy, balance, and consistency." },
    { id: "learning", label: "Continuous Learning", category: "personal", description: "Following curiosity, testing ideas, and turning information into understanding." },
    { id: "creative-projects", label: "Creative Projects", category: "personal", description: "Making useful and expressive things through focused experimentation." },
    { id: "life-systems", label: "Life Systems", category: "personal", description: "Lightweight routines that create more attention for meaningful work and play." }
  ],
  links: [
    ["knowledge-hub", "knowledge-systems"], ["knowledge-hub", "learning"], ["knowledge-hub", "life-systems"],
    ["strategy", "operations"], ["strategy", "customer-insight"], ["strategy", "investing"],
    ["operations", "automation"], ["operations", "financial-systems"], ["customer-insight", "generative-ai"],
    ["generative-ai", "knowledge-systems"], ["generative-ai", "automation"], ["generative-ai", "creative-projects"],
    ["knowledge-systems", "learning"], ["knowledge-systems", "media-library"], ["automation", "life-systems"],
    ["norrath", "raid-strategy"], ["norrath", "game-economy"], ["norrath", "media-library"],
    ["raid-strategy", "strategy"], ["raid-strategy", "strength"], ["game-economy", "financial-systems"],
    ["media-library", "visual-storytelling"], ["wardrobe-system", "visual-storytelling"], ["wardrobe-system", "life-systems"],
    ["visual-storytelling", "creative-projects"], ["visual-storytelling", "vehicle-design"],
    ["vehicle-design", "future-mobility"], ["vehicle-design", "maintenance"], ["maintenance", "home-projects"],
    ["future-mobility", "generative-ai"], ["future-mobility", "risk"],
    ["property-analysis", "home-projects"], ["property-analysis", "neighborhoods"], ["property-analysis", "investing"],
    ["home-projects", "creative-projects"], ["neighborhoods", "customer-insight"],
    ["investing", "financial-systems"], ["investing", "risk"], ["financial-systems", "life-systems"],
    ["risk", "recovery"], ["strength", "recovery"], ["strength", "nutrition"], ["nutrition", "recovery"],
    ["recovery", "life-systems"], ["learning", "creative-projects"], ["learning", "norrath"],
    ["maintenance", "risk"], ["customer-insight", "neighborhoods"], ["nutrition", "financial-systems"]
  ].map(([source, target]) => ({ source, target }))
};
